apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-api-prod-env-config
data:
  ENV: "prod"
  STRAVA_OAUTH_URL: "https://www.strava.com/oauth/authorize"
  STRAVA_TOKEN_URL: "https://www.strava.com/oauth/token"
