apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-api-prod-ksa
  namespace: fitness-api-prod
  annotations:
    iam.gke.io/gcp-service-account: fitness-api-prod-sa@ethans-services.iam.gserviceaccount.com
