apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-api-staging-env-config
data:
  ENV: "staging"
  IDENTITY_PROVIDER_URL: "http://identity.identity-staging.svc.cluster.local"
  JWT_ISSUER: "https://identity.ethanswan.com"
  STRAVA_OAUTH_URL: "https://www.strava.com/oauth/authorize"
  STRAVA_TOKEN_URL: "https://www.strava.com/oauth/token"
