apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fitness-api-staging-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/ethans-services/secrets/fitness_api_staging_database_url/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/ethans-services/secrets/fitness_api_staging_strava_client_id/versions/latest"
        path: "STRAVA_CLIENT_ID"
      - resourceName: "projects/ethans-services/secrets/fitness_api_staging_strava_client_secret/versions/latest"
        path: "STRAVA_CLIENT_SECRET"
      - resourceName: "projects/ethans-services/secrets/fitness_api_staging_trmnl_api_key/versions/latest"
        path: "TRMNL_API_KEY"
      - resourceName: "projects/ethans-services/secrets/fitness_api_staging_google_client_id/versions/latest"
        path: "GOOGLE_CLIENT_ID"
      - resourceName: "projects/ethans-services/secrets/fitness_api_staging_google_client_secret/versions/latest"
        path: "GOOGLE_CLIENT_SECRET"
      - resourceName: "projects/ethans-services/secrets/fitness_api_staging_hevy_api_key/versions/latest"
        path: "HEVY_API_KEY"
  secretObjects:
    - secretName: fitness-api-staging-secrets
      type: Opaque
      data:
        - objectName: "DATABASE_URL"
          key: DATABASE_URL
        - objectName: "STRAVA_CLIENT_ID"
          key: STRAVA_CLIENT_ID
        - objectName: "STRAVA_CLIENT_SECRET"
          key: STRAVA_CLIENT_SECRET
        - objectName: "TRMNL_API_KEY"
          key: TRMNL_API_KEY
        - objectName: "GOOGLE_CLIENT_ID"
          key: GOOGLE_CLIENT_ID
        - objectName: "GOOGLE_CLIENT_SECRET"
          key: GOOGLE_CLIENT_SECRET
        - objectName: "HEVY_API_KEY"
          key: HEVY_API_KEY
