apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-api-staging-ksa
  namespace: fitness-api-staging
  annotations:
    iam.gke.io/gcp-service-account: fitness-api-staging-sa@ethans-services.iam.gserviceaccount.com
