apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: fitness-api-staging
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: fitness-api-staging
      images:
        - alias: fitness-api
          imageName: us-central1-docker.pkg.dev/ethans-services/containers/fitness-api
          commonUpdateSettings:
            updateStrategy: newest-build
